name: backend-ci

on:
  push:
    branches: [ main ]
    paths:
      - backend/nginx/**

jobs:
  deploy-dev:
    uses: sawsansalah/demo-platform/.github/workflows/build-deploy.yml@v1.0.0
    with:
      microservice: backend-nginx
      env: dev
    secrets: inherit

  deploy-qa:
    uses: sawsansalah/demo-platform/.github/workflows/build-deploy.yml@v1.0.0
    with:
      microservice: backend-nginx
      env: qa
    secrets: inherit

